#arthematic operators using(+,-,*,**,/,//,%)
a=float(input("enter first number:"))
b=float(input("enter second number:"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Floor Division:",a//b)
print("Modulus:",a%b)
print ("power:",a**b)